#pragma once

#include "Identity.h"

NS_BEGIN(Engine)

typedef struct ENGINE_DLL DefaultAssetGuid
{
    static ASSET_GUID MESH_CUBE;
    static ASSET_GUID MESH_CUBE_TEX;
    static ASSET_GUID MESH_CUBE_NOR_TEX;
    static ASSET_GUID MESH_RECT;
    static ASSET_GUID MESH_SPHERE;
    static ASSET_GUID MESH_LINE;
    static ASSET_GUID MESH_RECT_NORTEX;

    static ASSET_GUID MATERIAL_VTXTEX;
    static ASSET_GUID MATERIAL_UI_DEFAULT;
    static ASSET_GUID MATERIAL_OUTLINE;
    static ASSET_GUID MATERIAL_OUTLINE_ANIM;

    static ASSET_GUID TEXTURE_UI_DEFAULT;
    static ASSET_GUID TEXTURE_BASEMAP_DEFAULT;
    static ASSET_GUID TEXTURE_NORMALMAP_DEFAULT;

    static ASSET_GUID SHADER_VTXCOL;
    static ASSET_GUID SHADER_VTXTEX;
    static ASSET_GUID SHADER_VTXMESH;
    static ASSET_GUID SHADER_VTXANIMMESH;
    static ASSET_GUID SHADER_VTXCUBE;
    static ASSET_GUID SHADER_VTXPARTICLEPOINT;
    static ASSET_GUID SHADER_VTXTRAIL;
    static ASSET_GUID SHADER_DEFERRED;
    static ASSET_GUID SHADER_FOG;
    static ASSET_GUID SHADER_SPEEDLINE;

    static ASSET_GUID FONT_UI_DEFAULT;

} DEFAULT_ASSET_GUID;

NS_END
